# Generated by Django 5.0.3 on 2024-04-07 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='image_url',
        ),
    ]
